title: Gillespy
description: GillesPy is a modeling toolkit for stochastic simulations of biochemical systems.
google_analytics: 
show_downloads: true
theme: jekyll-theme-modernist

gems:
  - jekyll-mentions
